/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface SsuiBackgroundVideo {
    /**
    * Should video autoplay
    */
    'autoplay': boolean;
    /**
    * Should video show controls
    */
    'controls': boolean;
    /**
    * Should video loop
    */
    'loop': boolean;
    /**
    * Should video be muted
    */
    'muted': boolean;
    /**
    * The overlay background
    */
    'overlayBackground': string;
    /**
    * The overlay background
    */
    'overlayOpacity': string;
    /**
    * Video poster while loading
    */
    'poster': string;
    /**
    * Should video be muted
    */
    'preload': string;
    /**
    * The object fit of the video Defaults to 'cover'
    */
    'videoFit': string;
    /**
    * The object position of the video Defaults to 'center center'
    */
    'videoPosition': string;
    /**
    * The video url(s) seperated by spaces
    */
    'videoSrcs': string;
  }
}

declare global {


  interface HTMLSsuiBackgroundVideoElement extends Components.SsuiBackgroundVideo, HTMLStencilElement {}
  var HTMLSsuiBackgroundVideoElement: {
    prototype: HTMLSsuiBackgroundVideoElement;
    new (): HTMLSsuiBackgroundVideoElement;
  };
  interface HTMLElementTagNameMap {
    'ssui-background-video': HTMLSsuiBackgroundVideoElement;
  }
}

declare namespace LocalJSX {
  interface SsuiBackgroundVideo extends JSXBase.HTMLAttributes<HTMLSsuiBackgroundVideoElement> {
    /**
    * Should video autoplay
    */
    'autoplay'?: boolean;
    /**
    * Should video show controls
    */
    'controls'?: boolean;
    /**
    * Should video loop
    */
    'loop'?: boolean;
    /**
    * Should video be muted
    */
    'muted'?: boolean;
    /**
    * The overlay background
    */
    'overlayBackground'?: string;
    /**
    * The overlay background
    */
    'overlayOpacity'?: string;
    /**
    * Video poster while loading
    */
    'poster'?: string;
    /**
    * Should video be muted
    */
    'preload'?: string;
    /**
    * The object fit of the video Defaults to 'cover'
    */
    'videoFit'?: string;
    /**
    * The object position of the video Defaults to 'center center'
    */
    'videoPosition'?: string;
    /**
    * The video url(s) seperated by spaces
    */
    'videoSrcs'?: string;
  }

  interface IntrinsicElements {
    'ssui-background-video': SsuiBackgroundVideo;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


